#!/bin/bash

find . -name "*.[cC][eE][rR][tT]" -o -name "*.[cCkKpP][rreE][tTeYmM]" -print -exec openssl x509 -text -noout -in {} \; 2>/dev/null > ~/x509.report.$(hostname).$(pwd | sed 's/\//./g').txt

grep -A1 "Not After" ~/x509.report.$(hostname).$(pwd | sed 's/\//./g').txt
