#!/bin/bash

find . -name "*.[dD][eE][rR]" -print -exec openssl x509 -inform der -text -noout -in {} \; 2>/dev/null > ~/x509.report.$(hostname).$(pwd | sed 's/\//./g').txt

grep -A1 "Not After" ~/x509.report.der.$(hostname).$(pwd | sed 's/\//./g').txt
