#!/usr/bin/env bash

grep -A3 Validity ~/x509.report.$(hostname).*.txt | tr -d '\n' | sed 's/\-\-/\n/g' | sed 's/            /|/g' | sed 's/        /|/g' | sed 's/|Validity/Certificate Info/g' | sort -u | sort -k14

